export const userData = [
    {
        _id: 'u102',
        username: 'AnnaS',
        password: 'annapass',
        fullname: 'Anna Smith',
        imgUrl: 'http://example.com/profile/anna.jpg',
        following: [],
        followers: [
            {
                _id: 'u107',
                fullname: 'Emily',
                imgUrl: 'http://example.com/profile/emily.jpg',
            },
        ],
        savedStoryIds: ['s102', 's105'],
    },
    {
        _id: 'u103',
        username: 'MichaelB',
        password: 'michael123',
        fullname: 'Michael Brown',
        imgUrl: 'http://example.com/profile/michael.jpg',
        following: [],
        followers: [
            {
                _id: 'u109',
                fullname: 'Alice',
                imgUrl: 'http://example.com/profile/alice.jpg',
            },
        ],
        savedStoryIds: ['s103', 's106'],
    },
    {
        _id: 'u104',
        username: 'ChrisJ',
        password: 'chrispass',
        fullname: 'Chris Johnson',
        imgUrl: 'http://example.com/profile/chris.jpg',
        following: [
            {
                _id: 'u110',
                fullname: 'Sarah',
                imgUrl: 'http://example.com/profile/sarah.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s104'],
    },
    {
        _id: 'u105',
        username: 'LindaG',
        password: 'linda123',
        fullname: 'Linda Gates',
        imgUrl: 'http://example.com/profile/linda.jpg',
        following: [
            {
                _id: 'u112',
                fullname: 'Kevin',
                imgUrl: 'http://example.com/profile/kevin.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s105'],
    },
    {
        _id: 'u106',
        username: 'DavidL',
        password: 'davidpass',
        fullname: 'David Lee',
        imgUrl: 'http://example.com/profile/david.jpg',
        following: [
            {
                _id: 'u114',
                fullname: 'Emma',
                imgUrl: 'http://example.com/profile/emma.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s106'],
    },

    // Commenters and Likers
    {
        _id: 'u107',
        username: 'EmilyC',
        password: 'emilypass',
        fullname: 'Emily',
        imgUrl: 'http://example.com/profile/emily.jpg',
        following: [
            {
                _id: 'u102',
                fullname: 'Anna Smith',
                imgUrl: 'http://example.com/profile/anna.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s102'],
    },
    {
        _id: 'u108',
        username: 'JohnD',
        password: 'john123',
        fullname: 'John',
        imgUrl: 'http://example.com/profile/john.jpg',
        following: [],
        followers: [],
        savedStoryIds: ['s102', 's104'],
    },
    {
        _id: 'u109',
        username: 'AliceM',
        password: 'alice123',
        fullname: 'Alice',
        imgUrl: 'http://example.com/profile/alice.jpg',
        following: [],
        followers: [
            {
                _id: 'u103',
                fullname: 'Michael Brown',
                imgUrl: 'http://example.com/profile/michael.jpg',
            },
        ],
        savedStoryIds: ['s103'],
    },
    {
        _id: 'u110',
        username: 'SarahK',
        password: 'sarahpass',
        fullname: 'Sarah',
        imgUrl: 'http://example.com/profile/sarah.jpg',
        following: [
            {
                _id: 'u104',
                fullname: 'Chris Johnson',
                imgUrl: 'http://example.com/profile/chris.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s104', 's105'],
    },
    {
        _id: 'u111',
        username: 'MikeL',
        password: 'mikepass',
        fullname: 'Mike',
        imgUrl: 'http://example.com/profile/mike.jpg',
        following: [],
        followers: [],
        savedStoryIds: ['s104'],
    },
    {
        _id: 'u112',
        username: 'KevinT',
        password: 'kevinpass',
        fullname: 'Kevin',
        imgUrl: 'http://example.com/profile/kevin.jpg',
        following: [
            {
                _id: 'u105',
                fullname: 'Linda Gates',
                imgUrl: 'http://example.com/profile/linda.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s105', 's106'],
    },
    {
        _id: 'u113',
        username: 'GraceW',
        password: 'grace123',
        fullname: 'Grace',
        imgUrl: 'http://example.com/profile/grace.jpg',
        following: [],
        followers: [],
        savedStoryIds: ['s105'],
    },
    {
        _id: 'u114',
        username: 'EmmaP',
        password: 'emmapass',
        fullname: 'Emma',
        imgUrl: 'http://example.com/profile/emma.jpg',
        following: [
            {
                _id: 'u106',
                fullname: 'David Lee',
                imgUrl: 'http://example.com/profile/david.jpg',
            },
        ],
        followers: [],
        savedStoryIds: ['s106'],
    },
]
